const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, payload) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld('api', {
  auth: {
    login: (creds) => invoke('auth:login', creds),
    changePassword: (payload) => invoke('auth:changePassword', payload),
  },
  settings: {
    get: () => invoke('settings:get'),
    update: (patch) => invoke('settings:update', patch),
  },
  products: {
    list: () => invoke('products:list'),
    create: (p) => invoke('products:create', p),
    update: (p) => invoke('products:update', p),
    remove: (id) => invoke('products:delete', id),
  },
  customers: {
    list: () => invoke('customers:list'),
    create: (c) => invoke('customers:create', c),
    update: (c) => invoke('customers:update', c),
    remove: (id) => invoke('customers:delete', id),
  },
  quotations: {
    list: () => invoke('quotations:list'),
    get: (id) => invoke('quotations:get', id),
    nextNumber: () => invoke('quotations:nextNumber'),
    create: (q) => invoke('quotations:create', q),
    update: (q) => invoke('quotations:update', q),
    remove: (id) => invoke('quotations:delete', id),
    updateStatus: (id, status) => invoke('quotations:updateStatus', { id, status }),
    markBilled: (id) => invoke('quotations:markBilled', id),
    markLost: (id) => invoke('quotations:markLost', id),
    markPending: (id) => invoke('quotations:markPending', id),
    latestOrDemo: () => invoke('quotations:latestOrDemo'),
  },
  quotePayments: {
    add: (p) => invoke('quotePayments:add', p),
    remove: (id) => invoke('quotePayments:delete', id),
    list: (quotationId) => invoke('quotePayments:list', quotationId),
  },
  advances: {
    list: (filters) => invoke('advances:list', filters),
    create: (a) => invoke('advances:create', a),
    update: (a) => invoke('advances:update', a),
    remove: (id) => invoke('advances:delete', id),
    summary: (empId) => invoke('advances:summary', empId),
    deductions: (filters) => invoke('advances:deductions', filters),
  },
  admin: {
    seedSampleData: () => invoke('admin:seedSampleData'),
    wipeAllData: () => invoke('admin:wipeAllData'),
  },
  invoices: {
    list: () => invoke('invoices:list'),
    get: (id) => invoke('invoices:get', id),
    nextNumber: () => invoke('invoices:nextNumber'),
    create: (inv) => invoke('invoices:create', inv),
    update: (inv) => invoke('invoices:update', inv),
    remove: (id) => invoke('invoices:delete', id),
    convertFromQuotation: (quotationId, extras) =>
      invoke('invoices:convertFromQuotation', { quotationId, extras }),
    receivables: () => invoke('invoices:receivables'),
  },
  payments: {
    add: (p) => invoke('payments:add', p),
    remove: (id) => invoke('payments:delete', id),
  },
  vendors: {
    list: () => invoke('vendors:list'),
    create: (v) => invoke('vendors:create', v),
    update: (v) => invoke('vendors:update', v),
    remove: (id) => invoke('vendors:delete', id),
  },
  incomes: {
    list: (filters) => invoke('incomes:list', filters),
    get: (id) => invoke('incomes:get', id),
    create: (i) => invoke('incomes:create', i),
    update: (i) => invoke('incomes:update', i),
    recordPayment: (id, amount) => invoke('incomes:recordPayment', { id, amount }),
    remove: (id) => invoke('incomes:delete', id),
    stats: (filters) => invoke('incomes:stats', filters),
  },
  expenses: {
    list: (filters) => invoke('expenses:list', filters),
    get: (id) => invoke('expenses:get', id),
    create: (e) => invoke('expenses:create', e),
    update: (e) => invoke('expenses:update', e),
    remove: (id) => invoke('expenses:delete', id),
    categories: () => invoke('expenses:categories'),
    stats: (filters) => invoke('expenses:stats', filters),
    recordPayment: (id, amount) => invoke('expenses:recordPayment', { id, amount }),
  },
  dashboard: {
    stats: () => invoke('dashboard:stats'),
    moneyForRange: (from, to) => invoke('dashboard:moneyForRange', { from, to }),
  },
  pdf: {
    export: (id) => invoke('pdf:export', id),
    preview: (id) => invoke('pdf:preview', id),
    designerPreview: (patch) => invoke('pdf:designerPreview', patch),
    previewInvoice: (id) => invoke('pdf:previewInvoice', id),
    exportInvoice: (id) => invoke('pdf:exportInvoice', id),
  },
  dialog: {
    pickLogo: () => invoke('dialog:pickLogo'),
    pickWatermark: () => invoke('dialog:pickWatermark'),
    pickReceipt: () => invoke('dialog:pickReceipt'),
  },
  reports: {
    monthlyTrend: (months) => invoke('reports:monthlyTrend', months),
    dashboardTrend: (granularity, count) => invoke('reports:dashboardTrend', { granularity, count }),
    dashboardTrendForRange: (from, to) => invoke('reports:dashboardTrendForRange', { from, to }),
    profitLoss: (filters) => invoke('reports:profitLoss', filters),
    cashflow: (filters) => invoke('reports:cashflow', filters),
    sales: (filters) => invoke('reports:sales', filters),
    gst: (filters) => invoke('reports:gst', filters),
    attendance: (filters) => invoke('reports:attendance', filters),
    payrollRegister: (filters) => invoke('reports:payrollRegister', filters),
    advancesOutstanding: () => invoke('reports:advancesOutstanding'),
    customers: () => invoke('reports:customers'),
    vendors: (filters) => invoke('reports:vendors', filters),
    credit: (filters) => invoke('reports:credit', filters),
    pdf: (payload) => invoke('reports:pdf', payload),
    pipeline: () => invoke('reports:pipeline'),
    pendingQuotations: (limit) => invoke('reports:pendingQuotations', limit),
  },
  shifts: {
    list: () => invoke('shifts:list'),
    create: (s) => invoke('shifts:create', s),
    update: (s) => invoke('shifts:update', s),
    remove: (id) => invoke('shifts:delete', id),
  },
  employees: {
    list: () => invoke('employees:list'),
    get: (id) => invoke('employees:get', id),
    create: (e) => invoke('employees:create', e),
    update: (e) => invoke('employees:update', e),
    remove: (id) => invoke('employees:delete', id),
  },
  attendance: {
    list: (filters) => invoke('attendance:list', filters),
    upsert: (a) => invoke('attendance:upsert', a),
    remove: (id) => invoke('attendance:delete', id),
    matrix: (period) => invoke('attendance:matrix', period),
  },
  leaves: {
    list: (filters) => invoke('leaves:list', filters),
    create: (l) => invoke('leaves:create', l),
    remove: (id) => invoke('leaves:delete', id),
  },
  payroll: {
    list: () => invoke('payroll:list'),
    get: (id) => invoke('payroll:get', id),
    entriesForEmployee: (employee_id) => invoke('payroll:entriesForEmployee', employee_id),
    runForEmployee: (employee_id, period_start, period_end, notes) =>
      invoke('payroll:runForEmployee', { employee_id, period_start, period_end, notes }),
    preview: (employee_id, period) => invoke('payroll:preview', { employee_id, period }),
    previewRange: (employee_id, period_start, period_end) => invoke('payroll:preview', { employee_id, period_start, period_end }),
    run: (period, notes) => invoke('payroll:run', { period, notes }),
    runRange: (period_start, period_end, notes) => invoke('payroll:run', { period_start, period_end, notes }),
    markPaid: (entry_id, paid_date) => invoke('payroll:markPaid', { entry_id, paid_date }),
    pay: (entry_id, amount, paid_date) => invoke('payroll:pay', { entry_id, amount, paid_date }),
    setAdvanceDeduction: (entry_id, amount) => invoke('payroll:setAdvanceDeduction', { entry_id, amount }),
    remove: (id) => invoke('payroll:delete', id),
    autoRunIfDue: () => invoke('payroll:autoRunIfDue'),
    recalculate: (id) => invoke('payroll:recalculate', id),
  },
});
